apiVersion: v1
kind: BuildConfig
metadata:
  name: scc-pipeline
spec:
  triggers:
    - type: GitHub
      github:
        secret: githubscc
    - type: Generic
      generic:
        secret: genericscc
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {

           stage ('Deploy DEV') {
             def userInput = input(
               id: 'userInput', message: 'Tag para promoção para DEV', parameters: [
               [$class: 'TextParameterDefinition', defaultValue: 'dev', description: 'Tag', name: 'tag']
             ])
             echo ("Tag: " +userInput)

             sh "oc project imagens"
             sh "oc tag imagens/scc:${userInput} dev-scc/scc:${userInput}"
             sh "oc project dev-scc"
             sh "oc delete bc,dc,svc,route -l app=scc"
             sh "oc new-app scc:${userInput}"
             sh "oc expose svc/scc"
           }


           stage ('Deploy HINT') {
             timeout(time:5, unit:'MINUTES') {
                input message: "Promover para HINT?", ok: "Promote"
             }

             def userInput = input(
               id: 'userInput', message: 'Tag para promoção para HINT', parameters: [
               [$class: 'TextParameterDefinition', defaultValue: 'hint', description: 'Tag', name: 'tag']
             ])
             echo ("Tag: " +userInput)

             sh "oc project dev-scc"
             sh "oc tag imagens/scc:${userInput} hint-scc/scc:${userInput}"
             sh "oc project hint-scc"
             sh "oc delete bc,dc,svc,route -l app=scc"
             sh "oc new-app scc:${userInput}"
             sh "oc expose svc/scc"
           }
        }

    type: JenkinsPipeline
    type: Generic
status:
  lastVersion: 0
